export const SAVE_QUERY_STATE = 'SAVE_QUERY_STATE';
export const SAVE_OBJECT_SURFFING_STATE = 'SAVE_OBJECT_SURFFING_STATE';

export const ACTION_STATES = [
  SAVE_QUERY_STATE,
  SAVE_OBJECT_SURFFING_STATE,
];
